server:
  port: 0
  shutdown: graceful

spring:
  application:
    name: waiting-service

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: waiting-service-group-out
      auto-offset-reset: latest
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      tags:
        application: ${spring.application.name} # ì—¬ëŸ¬ ì„œë²„ ì‹ë³„ì„ ìœ„í•œ íƒœê·¸

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true


logging:
  level:
    # ğŸ‘‡ Kafka ì„¤ì •ê°’(AbstractConfig) ë¡œê·¸ë§Œ ì™ ê³¨ë¼ì„œ WARN ì´ìƒì¼ ë•Œë§Œ ì¶œë ¥í•˜ê²Œ ë³€ê²½
    org.apache.kafka.common.config: WARN

    # (ì„ íƒ) Kafka í´ë¼ì´ì–¸íŠ¸ ì „ì²´ ë¡œê·¸ë¥¼ ì¢€ ì¡°ìš©íˆ ì‹œí‚¤ê³  ì‹¶ë‹¤ë©´
    org.apache.kafka.clients.producer: WARN
    org.apache.kafka.clients.consumer: WARN

app:
  kafka:
    topics:
      waiting-events: waiting-events
  feign:
    restaurant:
      url: "http://localhost:6000/restaurants"


resilience4j:
  bulkhead:
    instances:
      restaurantService: # [ì¤‘ìš”] ì´ ì´ë¦„ì´ ë‚˜ì¤‘ì— ì–´ë…¸í…Œì´ì…˜ì˜ nameê³¼ ì¼ì¹˜í•´ì•¼ í•©ë‹ˆë‹¤.
        maxConcurrentCalls: 20  # ë™ì‹œì— 20ê°œ ìŠ¤ë ˆë“œê¹Œì§€ë§Œ ì§„ì… í—ˆìš©
        maxWaitDuration: 100ms  # ê½‰ ì°¼ì„ ë•Œ 0.1ì´ˆë§Œ ëŒ€ê¸°í•˜ê³  ë°”ë¡œ ê±°ì ˆ(Fast Fail)

  # (ì„ íƒ) ì„œí‚· ë¸Œë ˆì´ì»¤ ì„¤ì •ë„ ì˜¤ë²„ë¼ì´ë”©í•˜ê³  ì‹¶ë‹¤ë©´ ì¶”ê°€
  circuitbreaker:
    instances:
      restaurantService:
        baseConfig: default # ê³µí†µ ëª¨ë“ˆì˜ ì„¤ì •ì„ ìƒì†ë°›ìŒ
        slidingWindowSize: 20 # ì‹ë‹¹ í˜¸ì¶œì€ ë¹ˆë²ˆí•˜ì§€ ì•Šìœ¼ë‹ˆ ìœˆë„ìš° ì‚¬ì´ì¦ˆë¥¼ ì‘ê²Œ ì¡°ì •