spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # url도 환경변수로 뺄 수 있지만, 로컬은 보통 고정이므로 적어도 무방합니다.
    url: jdbc:postgresql://localhost:5432/waiting_service_db

    # [핵심] 환경 변수로부터 주입받습니다. 없으면 기본값(root)을 씁니다.
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # 실무 DB는 update/create 금지! (검증만 수행)

    # 2. Redis (storage-redis 모듈용)
  # 2. Redis (storage-redis 모듈용)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:} # 없으면 빈 문자열(비밀번호 없음)

  # 3. Kafka (storage-kafka 모듈용)
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: waiting-service-group-home
      auto-offset-reset: latest