server:
  port: 8761

spring:
  application:
    name: discovery-service
  threads:
    virtual:
      enabled: true # Java 25 ?? ??? ???? ?? ???? ?? ???

eureka:
  instance:
    hostname: localhost
  client:
    # ?? ??? ??? ????? ??? ??? ??? ???? false ??
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # ?? ?? ? ??? ?? ?? ??? ??? ?? ??
    wait-time-in-ms-when-sync-empty: 0
    # ????? ???? ?? ? ?? ??? ???? ?? ?????,
    # ?? ????? ?? ??? ?? ?? ?? ? ????.
    enable-self-preservation: false