server:
  port: 8083

spring:
  application:
    name: notification-service
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: notification-service-group # 식당 서비스와 다른 그룹 ID 사용!

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# 우리가 사용할 커스텀 설정
app:
  kafka:
    topics:
      waiting-events: waiting-events

    listener:
      type: batch #핵심! (기본값은 single)
      consumer:
        max-poll-records: 500 # 한 번에 최대 500개까지 가져옴
        fetch-min-size: 100 # (선택) 데이터가 적으면 좀 기다렸다가 뭉쳐서 가져옴

  slack:
    webhook-url: ${WEBHOOK_URL:}