spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/restaurant_service_db

    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # 실무 DB는 update/create 금지! (검증만 수행)

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:} # 없으면 빈 문자열(비밀번호 없음)

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: waiting-service-group-home
      auto-offset-reset: latest