server:
  port: 19090

spring:
  application:
    name: auth-service

app:
  jwt:
    # 아래 키는 예시입니다. (실제 운영에선 환경변수로 관리 필수)
    # 터미널에서 `openssl rand -base64 64` 명령어로 생성한 값을 넣으세요.
    secret: "vMFZ7YkY5+JjK3Hq8Lw9XzC2Vb4N/mQaR1TsD6EfG8UoWpI0OxLrYtZ3V5KjH9NcXyZ1QaW2EcR4VtB6NkM8==
"
    expiration: 3600000 # 1시간 (3600초 * 1000ms)