services:
  frontend:
    image: booster/frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: booster-frontend
    restart: no
    ports:
      - "3300:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - booster-network

networks:
  booster-network:
    external: true
    name: booster-network